### ISSUE TITLE
TUTORIAL can not be closed

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#10]
If Tutorial menu has been opened - it can not be closed. Black screen appeared with a string "Loading..." Need to exit to lobby and to enter the game again.

**Comment by tbox1911** [comment]
should be fixed in the latest version

**Comment by Varrkan82** [comment]
> fixed in a previous release

Not fixed. Still present.

**Comment by tbox1911** [comment]
I've just test with the latest pbo (in build) and I can't reproduce the issue
i'll try to find the commit

**Comment by tbox1911** [comment]
could be in file:
scripts\client\ui\intro.sqf
scripts\client\ui\tutorial_manager.sqf
scripts\client\spawn\redeploy_manager.sqf

try to update these files
(if the issue persist send me the pbo)

**Comment by Varrkan82** [comment]
> could be in file:
> scripts\client\ui\intro.sqf
> scripts\client\ui\tutorial_manager.sqf
> scripts\client\spawn\redeploy_manager.sqf
> 
> try to update these files
> (if the issue persist send me the pbo)

An only difference I've found - it are my translations and I've added a one extra item to tutorial_manager.sqf
![image](https://user-images.githubusercontent.com/7004992/103666793-c0422a00-4f7d-11eb-965b-b82addfe2cba.png)
Here is the link to my latest PBO. Select an "ІНСТРУКЦІЯ" menu item.
https://mega.nz/file/9NU0jLaD#kaldqpYhp0wCFVimmwVqpsW1HN7bH4oVo8HX3123aNY

**Comment by tbox1911** [comment]
ok, I'll test on my side

**Comment by tbox1911** [comment]
strange, tested with your pbo, and it work fine. (in lang fr/en)
It take your idea to put the tip'n trick in tutorial

can you test in english ?
i keep investigate

**Comment by Varrkan82** [comment]
> strange, tested with your pbo, and it work fine. (in lang fr/en)
> I take your idea to put the tip'n trick in tutorial
> 
> can you test in english ?
> i keep investigate

I'll try. Thanks.

**Comment by tbox1911** [comment]
also try, in local mode (hosted)

because in intro.sqf, I wait for the player read briefing
```
if (isMultiplayer) then {
	waituntil {(time > 2) && (getClientStateNumber >= 10) && (getClientState == "BRIEFING READ")};
```

**Comment by tbox1911** [comment]
ok, i'm able to reproduce

**Comment by Varrkan82** [comment]
> ok, i'm able to reproduce

Need you some action from my side?

**Comment by Varrkan82** [comment]
> I take your idea to put the tip'n trick in tutorial

Please, pay attention, I'm translating to Ukrainian, not to Russian. Arma just not supported Ukrainian and I need to replace Russian in stringtable.xml

**Comment by Varrkan82** [comment]
Confirmed fix.
