### ISSUE TITLE
Been having issues with vanilla Arma 3 NATO loadout being applied to new users in spite of SOG presets defined in server cfg. Could this be the problem - a typo of an upercase U in "preprocessFileLineNumbers"? If not, how do I go about fixing this? Thanks

### ISSUE THREAD

**Issue by JonnyDeadly** [tbox1911/Liberation-RX#101]
https://github.com/tbox1911/Liberation-RX/blob/14103cc7d94b5d05884c9021b8b7ba7d9f785be5/core.liberation/scripts/client/spawn/redeploy_manager.sqf#L166

**Comment by tbox1911** [comment]
hi,

the parameters in charge of player loadout is "ForcedLoadout"
must be set to 1, to use mod template loadout.

please, send your server configuration and the last server rpt file to investigate

note:  in sqf, script case doesn't matter ;)

**Comment by JonnyDeadly** [comment]
Thanks for letting me know. :) While I have your attention, is there a way to change the FOB startup vehicle on Cam Lao Nam with the SOG assets as opposed to Vanilla? I see these options in the server cfg but they're vanilla options and there actually is no startup truck for the aircraft carrier on Cam Lao Nam as far as I know. Thanks

**Comment by tbox1911** [comment]
I'll take a look on FobType (truck/heli) params

I I catch you well, you want to be able to spawn (SoG) FOB truck on the CamLao carrier ?

**Comment by JonnyDeadly** [comment]
Hi

Thanks for getting back. I was actually meaning how to load the FOB into the chocktaw on Cam Lao Nam with SOG assets. What I've found is that the FOB (cargo crate) loads a while (quite long although I'm not sure) after the chocktaw has been moved from the carrier to a place on the map. As long as it doesn't take too long to spawn in, I'm fine with that. :)

**Comment by JonnyDeadly** [comment]
FobType = 0;                      // The Startup Fob Vehicle - [default 0] - values = [1,0] - Text {Huron,Truck}
			HuronType = 0;                    // The type of Huron - [default 0] - values = [0,1,2,3] - Text {Disabled, "CH-67 Huron", "CH-49 Mohawk", "UH-80 Ghost Hawk"}
			
			FobType is Huron and Huron Type is disabled, as there seems to be only vanilla options available for the value?

**Comment by tbox1911** [comment]
at very fist , you just have to use mouse menu "load object into.." to load the FOB box in the chocktaw, and the fly where you want

**Comment by tbox1911** [comment]
just to be sure you use correct "ModPresetWest" settings ?

**Comment by JonnyDeadly** [comment]
Yes, 19 and 22 for East. All the assets are spawned in as they should be, no issues whatsoever. Just unsure about the first FOB as it spawns on the same location as the Chocktaw, just later in the game? This means the FOB can't be set up for a while.

**Comment by tbox1911** [comment]
at beginning you can pilot the Chocktaw, so you have to load (wheel menu on fob crate) the FOB box into the Chocktaw.

the Chocktaw is not like a FOB truck, it's a mobile respawn that can be loaded with the first fob box

**Comment by JonnyDeadly** [comment]
Thanks for explaining all of this to me, it means a lot. But from my experience the Chocktaw actually spawns on the exact same spot as the FOB cargo crate, meaning it takes longer for the crate to load because the Chocktaw has to be detected clear of it? or am I totally missing the ball here? :D

**Comment by tbox1911** [comment]
if no bug spawn!
there is two places on the carrier, (pretty close) one with pallet for the FOB box and closeby the Chocktaw

**Comment by JonnyDeadly** [comment]
Oh okay maybe I just wasn't seeing it nearby. I've only been running the server for a day so I'm still pretty not used to the gamemode. I used to play Liberation a lot on Unsung years ago, but I have a bad memory of how it all works :P

**Comment by tbox1911** [comment]
no worry! try a little and report me if you found issue 👍
