### ISSUE TITLE
建造菜单怎么修改

### ISSUE THREAD

**Issue by xudaozai** [tbox1911/Liberation-RX#102]
你好作者建造菜单怎么改 在那个地方我并没有找到  谢谢

**Comment by tbox1911** [comment]
Hi,

you can change the construction menu by editing the file "classnames_west.sqf" in the mod_template folder.

regards,

**Comment by xudaozai** [comment]
哦，太谢谢你了，你真是我见过最棒的作者。我会一直支持你的

**Comment by tbox1911** [comment]
Thank you very much !
you're welcome
