### ISSUE TITLE
How to add more vehicles?

### ISSUE THREAD

**Issue by 3312567114** [tbox1911/Liberation-RX#103]
Q1:How can i do to add more additional vehicles to the build menu?

Q2: I start a server with RHSUSAF.I mount RHSUSAF in "-mod=",but It seems that there is no RHSUSAF vehicles in build menu,what is going on?

**Comment by tbox1911** [comment]
Q1: edit file "classnames_west.sqf" in mod_template folder

Q2: you have to select which faction yo wan to use (in lobby/server cfg)
GRLIB_mod_west / GRLIB_mod_east

**Comment by 3312567114** [comment]
OK,thank you both the questions are solved.I can see them in the build menu

I'm using the cfg:RHS_USAF ,so if i want to add more Vehicles,just edit in mod_template\RHS_USAF\classnames_west.sqf.

And can i also add vehicles in other mods to the same file in mod_template\RHS_USAF\classnames_west.sqf?

**Comment by tbox1911** [comment]
as you see, each mod has its own folder, and in this folder you can configure east and west class name (depending if you are playing faction or against faction)

so, 
edit mod_template\RHS_USAF\classnames_west.sqf    (when you play as USAF)
edit mod_template\RHS_AFRF\classnames_east.sqf     (when you play against AFRF)

or
edit mod_template\A3_BLU\classnames_west.sqf    (when you play as classic Bluefor)
edit mod_template\CP_TA\classnames_east.sqf     (when you play against CUP Takistani army)



the same apply to all folder in mod_template
you have to edit only the file concerned by your selection

**Comment by 3312567114** [comment]
I see.Thank you for your answer. This is very helpful for me to personalize this task.
