### ISSUE TITLE
Zeus editor when playing

### ISSUE THREAD

**Issue by 3312567114** [tbox1911/Liberation-RX#104]
When I use the Zeus editor to place some buildings, it seems that only some of them remain after restarting.  

Is this because these buildings are not on the white list? What can I do to keep these buildings?

**Comment by tbox1911** [comment]
- only objects near FOB will be saved
- not all objects can be saved
- most of object must be initialized by the game (not zeus directly)
- use the integrated Admin menu for spawning vehicles

**Comment by 3312567114** [comment]
oh,yes. I was using zeus to make my fob look better,but after restarting,only some of these objects, such as sandbags, remain.

It seems that it will not be saved if it is not in the building menu.(Is that how it works?)
(Just like the green military cargo warehouse will be preserved, while the brown one will not)

So I wonder how to make all buildings within FOB range can be saved.

**Comment by tbox1911** [comment]
they must add the object in the building list:
buildings_west = []
or
buildings_east = []

note: some objects have special LRX properties and must be created by the game and not directly by Eden.
as long as you only using building object, it should be fine

**Comment by 3312567114** [comment]
okay,If I use the building menu to create them, and then use Zeus to put them in position, is that ok?

**Comment by tbox1911** [comment]
yep, it should work, you also can use the 'move' action menu
