### ISSUE TITLE
Damage counted (message "Watch your fire" appeared) if landing or flying up alone in an aircarft.

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#11]
Damage warning appear if a single player flying up or landing in Helicopter or Aircraft

**Comment by tbox1911** [comment]
fix commited

**Comment by Varrkan82** [comment]
Looks like it fixed, but will test it more for a day or tow. Thanks. I'll close an issue if it will be all fine.

**Comment by Varrkan82** [comment]
Fixed
