### ISSUE TITLE
Mobile Respawn Not Showing on Deploy List

### ISSUE THREAD

**Issue by Lcreager** [tbox1911/Liberation-RX#112]
When the EnableLock parameter is set to 0, Mobile Respawn trucks do not show up in the Deployment menu.

It seems like the issue is with the following check in the F_getMobileRespawns.sqf function:
`_x getVariable ["GRLIB_vehicle_owner", ""] == _playerId &&`

**Comment by tbox1911** [comment]
Hi,
Thanks a lot for reporting,

I'll fix it asap. I let's you know when it's done




Le sam. 8 avr. 2023 à 06:04, Louis Creager ***@***.***> a
écrit :

**Comment by tbox1911** [comment]
hi,
I've make some test and, it seems to work as expected.
I see respawn truck/heli in the list

maybe you hit the  maximum spawn points per player limit ?
check the "Spawn Point limit per player." in parameter
(or server param MaxSpawnPoint)

note: locked or abandoned vehicles are not show
