### ISSUE TITLE
Please add Pacific Side

### ISSUE THREAD

**Issue by dfxss** [tbox1911/Liberation-RX#114]
Please add Pacific Side

**Comment by dfxss** [comment]
Pacific CSAT

**Comment by tbox1911** [comment]
can you send me the link to the mod please (steam workshop preferred)

**Comment by dfxss** [comment]
Liberation-RX

**Comment by tbox1911** [comment]
you mean CSAT with Urban camo ?

**Comment by dfxss** [comment]
OK Thanks
Maybe You Can add the Pacific Side (NATO CSAT)
and add the Aegis MOD addons (https://steamcommunity.com/sharedfiles/filedetails/?id=949252631&searchtext=aegis)

**Comment by tbox1911** [comment]
hi, not much time to do template, try to make it it's easy !
come on our discord, to see how to make it :)
