### ISSUE TITLE
ACE Arsenal is broken

### ISSUE THREAD

**Issue by sturmalex** [tbox1911/Liberation-RX#116]
Hi there,

when accessing the arsenal with ACE enabled and e.g. RHS US vs RHS RU the whole content of weapons. Vanilla, DLC, CDLC and other Mods is available despite having "strict" mode set in parameters.

The Items are not selectable though, when you select them and exit the arsenal the item disappears

thanks and BR
Alex

**Comment by sturmalex** [comment]
I changed some coding to print all black and all whitelisted items., while using Global Mobilisation and ACE:

`"Whitelist: "
 9:01:18 "Current element: B_Kitbag_Base"
 9:01:18 "Current element: B_Parachute"
 9:01:18 "Current element: gm_ge_army_medbox"
 9:01:18 "Current element: gm_ge_army_medkit"
 9:01:18 "Current element: gm_repairkit_01"
 9:01:18 "Current element: MineDetector"
 9:01:18 "Current element: Binocular"
 9:01:18 "Current element: ItemCompass"
 9:01:18 "Current element: ItemMap"
 9:01:18 "Current element: ItemRadio"
 9:01:18 "Current element: gm_watch_kosei_80"
 9:01:18 "Current element: Bandage"
 9:01:18 "Current element: HandGrenade"
 9:01:18 "Current element: MiniGrenade"
 9:01:18 "Current element: ATMine_Range_Mag"
 9:01:18 "Current element: SatchelCharge_Remote_Mag"
 9:01:18 "Current element: SLAMDirectionalMine_Wire_Mag"
 9:01:18 "BlackList: "
 9:01:18 "Current element: gm_fagot_launcher_weaponBag"
 9:01:18 "Current element: gm_milan_launcher_weaponBag"
 9:01:18 "Current element: gm_mg3_aatripod_weaponBag"
 9:01:18 "Current element: gm_p2a1_launcher_blk"
 9:01:18 "Current element: gm_gc_army_medbox"
 9:01:18 "Current element: gm_gc_army_medkit"
 9:01:18 "Current element: gm_gc_army_burnBandage"
 9:01:18 "Current element: gm_gc_army_gauzeBandage"
 9:01:18 "Current element: gm_gc_army_gauzeCompress"`

Maybe I dont understand the LAR Addon enough but shouldnt there be all items starting with "gm_" in the whitelist?

In any event, the Arsenal still shows items from RHS, Vanilla etc. I forgot to mention that if the player choses e.g. a vanilla weapon: when he leaves the arsenal the weapon get removed/not selected. Therefore the filter after closing the arsenal kind of works, its the display, that is off.

**Comment by tbox1911** [comment]
hello, thanks, I'll look a that !

**Comment by sturmalex** [comment]
Hi tbox, 

merci beaucoup! :-) 

Also I realized when using ACE Arsenal the Mission switches from Strict to Strict+ Mode. Is there any reason to that?

I tinkered a bit.....

File: liberationArsenal.sqf.

If you dont pass 
`if (GRLIB_ACE_enabled) then { [myLARsBox, true, false] call ace_arsenal_fnc_initBox };`
in Line 72 
but pass 
`if (GRLIB_ACE_enabled) then { [myLARsBox, GRLIB_whitelisted_from_arsenal, false] call ace_arsenal_fnc_initBox };` 
in line 86 it shows the correct items.


In this case ACE Items are missing though, I added a logic to the ace filtering to (hopefully) add all ACE Items to the whitelist.

I tested it and: did you know that you can stuff 240 Bananas into the Eagle Bag? lol.

I have created a solution IMO
Check my Pull request:
https://github.com/tbox1911/Liberation-RX/pull/117

BR
Alex

**Comment by sturmalex** [comment]
Okay, I just realized, that there are weapons like launchers added by ACE... sigh... these shouldnt be there of course

**Comment by tbox1911** [comment]
thanks buddy!

I'll merge that, feel free to come on our discord to chat about mission scripting
https://discord.gg/uCRzJ7wauR

**Comment by tbox1911** [comment]
I commit an update about ace filter 
update and tell me if it's ok
