### ISSUE TITLE
Vehicles going into forever re-arming and can't be placed in a Virtual Garage.

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#12]
Tried on F118 Aircraft. It is re-arming too long (once it takes around a 15 minutes) or forever. While re-arming - it is can not be placed to a Virtual Garage.

**Comment by tbox1911** [comment]
fix a bug in the reammo counter

vehicle must wait 5 minutes to rearm

**Comment by Varrkan82** [comment]
> fixed in a previous release
> 
> vehicle must wait 5 minutes to rearm

Please, could you give me a link to fix. Seems like "previous release" you mean it is a yesterday commit a0a8f664e which I've already tried and it won't work.

**Comment by tbox1911** [comment]
it was in
Latest commit 529575f 2 days ago

i'll  double check rearm veh on my side

**Comment by Varrkan82** [comment]
> it was in
> Latest commit [529575f](https://github.com/tbox1911/Liberation-RX/commit/529575fcfd22a40ac5e5aaebf5e10e3d6262a289) 2 days ago
> 
> i'll double check rearm veh on my side

Doesn't see there anything about a 5 minutes. Are you sure?

**Comment by tbox1911** [comment]
yep, _cooldown = 20;

**Comment by Varrkan82** [comment]
> yep, _cooldown = 20;
> 
> I found another bug in this code, cooldown reset too fast
> I'll fix it

I thought its in a seconds.

**Comment by tbox1911** [comment]
it was 20 time sleep 15 (seconds)
push a fix for that, plus add message with time remaining ;)

**Comment by Varrkan82** [comment]
> it was 20 time sleep 15 (seconds)
> push a fix for that, plus add message with time remaining ;)
> 
> the previous issue only occur if you are close to reammo service (fob, hurron box)

This issue fixed. At least the plane can be putted to virtual garage. But re-arming now works in random cases. It could to start rearming and when the counter become the end - it starts to count again and so on. In other cases the re-arming can not start at all and vehicle could be re-armed only when putted into garage.

**Comment by tbox1911** [comment]
hmmm, I don't like the actual logic,  I'll rewrite this code soon :)

**Comment by tbox1911** [comment]
test with the latest commit, should be fine now

**Comment by Varrkan82** [comment]
UAV - can not be re-armed just after landing. It still need to be placed to VG, after it removed from VG - it is already re-armed? but the countdown started.
Land vehicles (tested with a tank) - countdown continues to count if a vehicle moves away from the Ammo box. Re-arming do not completed, but the counter is running.

**Comment by tbox1911** [comment]
I update the code to handle theses cases, you be fine now ! (i hope)
please test

add some doc: https://forums.bohemia.net/forums/topic/217186-release-liberation-rx/?do=findComment&comment=3427175

**Comment by Varrkan82** [comment]
Fix confirmed
