### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Zeereen** [tbox1911/Liberation-RX#133]
Is there a changelog or something somewhere? I have a somewhat older copy of the mission from 0.9XX few months ago and I want to understand what changes that would be breaking since I see the major version number has been bumped from 0 to 1. 

The github releases page is unhelpful as it seems to show only the current version and previous 2 versions. Looking at the commit history was also unhelpful as the history appears to be forcibly rewritten or rebased, thus losing historical changes.

**Comment by Varrkan82** [comment]
> Is there a changelog or something somewhere? I have a somewhat older copy of the mission from 0.9XX few months ago and I want to understand what changes that would be breaking since I see the major version number has been bumped from 0 to 1.
> 
> The github releases page is unhelpful as it seems to show only the current version and previous 2 versions. Looking at the commit history was also unhelpful as the history appears to be forcibly rewritten or rebased, thus losing historical changes.

You can find something like a changelog here in a forum thread https://forums.bohemia.net/forums/topic/217186-release-liberation-rx/?do=findComment&comment=3475227 

Also - look into commit names here in GitHub.

**Comment by tbox1911** [comment]
hi, no there is no 'complete' changelog, the commit history was too big to keep it.

I suggest you to move on latest version, many bug fix and new features

**Comment by Zeereen** [comment]
Thank you @Varrkan82 for linking the forum thread. I assume this particular post must be where it transitioned from 0.9XX to 1.X (https://forums.bohemia.net/forums/topic/217186-release-liberation-rx/?page=30&tab=comments#comment-3474400)

This is exactly what I needed to know; from what that post says, it WILL BE **NOT** backwards compatible with my current 0.9XX save, I will hold off on updating it until I finish my current play-through. Will definitely update for the next run. 

@tbox1911 Instead of relying on commit history, could there be a CHANGELOG.md file? That way, we won't have to deal with github file limits/release assets limitations?
