### ISSUE TITLE
How  to show MOTD in the game?

### ISSUE THREAD

**Issue by rushfly** [tbox1911/Liberation-RX#136]
The MOTD I defined in server.cfg can't displayed in game. And I sure the format of message is right. 
Or should I figure it out through another way?

**Comment by tbox1911** [comment]
as an example, here what I use in my server.cfg

motd[] =
{
	"","",
	"","",
	"","",
	"","",
	"Welcome to my Liberation Arma 3 Server","",
	"","",
	"You are looking for fun ?- Join us Now !",
	"","",
	"Only firendly people allowed !!","",
	"",""
};
motdInterval = 5;  


note:
The display of the motd is fully managed by the arma server, the mission itself has nothing to do

**Comment by Varrkan82** [comment]
Just notice - MOTD displayed as a line in a text chat. Line length is limited. ``motdInterval`` is a parameter, which regulates an interval between displaying an each line of text.

**Comment by rushfly** [comment]
Thank you for all of your answers!
 I have some other questions. What is the character limit for a line? Does it support non-ASCII character sets？

**Comment by tbox1911** [comment]
I don't know the max size, 
I think it's ascii only, but you can try others character sets.
plz report if it work

**Comment by Varrkan82** [comment]
> Thank you for all of your answers! I have some other questions. What is the length limit for a line? Does it support non-ASCII character sets？

Chat messages are transferred as a String. From this https://community.bistudio.com/wiki/String we see it is limited to 2056 characters. It supports non-ASCII symbols, but message length decreased dramatically if you do so. From my experience - it will be limited just around a 30-50 symbols. Just to be honest - I've never tried to check a real length using ASCII symbols ))
