### ISSUE TITLE
Recycling Vehicle Ammo crates does not grant Score points anymore

### ISSUE THREAD

**Issue by MrDj200** [tbox1911/Liberation-RX#138]
The game randomly stopped giving score points for recycling Vehicle Ammo Crates (Any faction).
We did not update the mission, it just stopped working suddenly today.
It's not just one player, it's several.
Ammo is still being given

**Comment by tbox1911** [comment]
note: the extra reward of 10xp when recycling an ammo box is here to help new players or low rank.

it stop after you reach the "Captain" rank, you still have ammo reward of course

**Comment by MrDj200** [comment]
I see, I did not know that. Is that noted anywhere?

**Comment by MrDj200** [comment]
Now that I think about it, I'm not Captian yet, but still didn't get xp points. 
Once I'm back in Arma, I'll do some tests, and if I find that ranks below captian don't get it, I'll reopen this and let you know

**Comment by MrDj200** [comment]
Okay, after further testing, you don't get the points starting with Sergeant.

And also, is there a way to just enable that it gives points to all ranks?
My groups playstyle just doesn't work otherwise. We wouldn't be getting enough points.
Already had to cheat to build a fob so we didn't have to go across the map every time we had to rearm.
We captured half of Altis, but still can't legitimately build a new fob, or maybe we're just missing something I guess

**Comment by tbox1911** [comment]
"is there a way to just enable that it gives points to all ranks?" , I don't think it's a good idea!

note: taking XP in RX is pretty easy:
- salvage wreck
- bring prisoners to fob
- do side missions !

**Comment by MrDj200** [comment]
sadly, most of my players don't have that much time/patience. 
Guess I'll just continue using the admin menu to "fix" that.

**Comment by Varrkan82** [comment]
> sadly, most of my players don't have that much time/patience.

For that purpose there is an option to save rank between mission restarts. So players can get the ranks during a short sessions.

**Comment by MrDj200** [comment]
It would still take some of them a few months like that. And we don't play that long on 1 map. 
For Malden we took a few days because I had to teach some people how to arma, but now we're close to finishing Altis. So that wouldn't really help the people that only play occasionally.

**Comment by MrDj200** [comment]
![image](https://github.com/tbox1911/Liberation-RX/assets/5685500/2b42db8b-fda2-499c-97b5-65b6a7adc61b)

Looks like there is a formatting issue
