### ISSUE TITLE
Sometimes Loadouts are not saved when rejoining

### ISSUE THREAD

**Issue by MrDj200** [tbox1911/Liberation-RX#139]
When rejoining the server, sometimes it does not load the old loadout of the player, but just the default loadout.
I have not found a way to replicate it reliably.
It happens to everyone occasionally, no matter which slot they chose

**Comment by tbox1911** [comment]
you have to be alive (not wounded) when you disconnect to recover your loadout.

the server must not be restarted when there is players connected.

the game save when the last player disconnect

**Comment by MrDj200** [comment]
do patched up ace wounds count towards the wounds you mention?
Aka. do I have to fully heal everyone before disconnecting?

If yes, maybe check where someone logs out, so that when you log out right next to a base, it gets saved anyways

**Comment by MrDj200** [comment]
I did several tests, and even when someone is fully healed, no remaining wounds at all, the loadout still doesn't save sometimes.

**Comment by tbox1911** [comment]
a last thing, on a dedicated server there is a cooldown of 300 sec of uptime, before the server can save

no need to be close a fob or slightly wounded (ace patched) 

look at your server log, there is info of player save (squad / loadout)

**Comment by MrDj200** [comment]
Even after hours of uptime, people still regularly loose their loadouts.
Would it be possible to add a "Save" Action on the Sign at FOB's for example?
Or even just a button in the Extended Options where view distance etc. are located as well

**Comment by tbox1911** [comment]
yes, I'll add a save button at fob
