### ISSUE TITLE
Can't join on empty server

### ISSUE THREAD

**Issue by SpaceKoi89p** [tbox1911/Liberation-RX#143]
When the server I'm currently playing on is empty and hasn't been been restarted in a while it give me a short loading screen and puts me back in role selection. I'm the only one on this servers players that has this issue.
I can fix it by going into resource monitor and halting the process for a few seconds when entering the loading screen.

**Comment by tbox1911** [comment]
can you share the client and server rpt file (log files)

**Comment by SpaceKoi89p** [comment]
[Arma3_x64_2023-06-28_13-26-54.zip](https://github.com/tbox1911/Liberation-RX/files/11893636/Arma3_x64_2023-06-28_13-26-54.zip)
Starting at 13:41:03 is when I tried to join a few times and then the last two attempts are with my "fix" of halting the process.
`:48  Mission directory: mpmissions\__cur_mp.Altis\
CallExtension 'DiscordRichPresence' could not be found
13:42:49 [CBA] (xeh) INFO: [603926,11980.7,0] PreInit started. v3.15.8.220912
13:42:49 [CBA] (settings) INFO: Reading settings from settings file.
13:42:49 [CBA] (settings) INFO: Finished reading settings from settings file.
13:42:49 [CBA] (settings) INFO: Mission Config: File [cba_settings.sqf] loaded successfully.
13:42:49 [CBA] (xeh) WARNING: One or more children of class Air do not support Extended Event Handlers. Fall back to loop.
13:42:49 [ACE] (common) INFO: Parsed Settings Configs [1.0 ms]
13:42:49 [CBA] (xeh) INFO: [603926,11981.2,0] PreInit finished.
PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
13:42:50 Strange convex component548 in a3\structures_f_enoch\military\radar\mobileradar_01_radar_ruins_f.p3d:geometryFire
Error: Wheel reference not initialized
Error: Wheel reference not initialized
Error: Wheel reference not initialized
Error: Wheel reference not initialized`
Is that the admin got when I tried to connect.

**Comment by tbox1911** [comment]
you your server is using 
persistent     = 0;

**Comment by SpaceKoi89p** [comment]
Does persistence keep ai loaded so when no is on server i.e. do ai capture cities/bases? The admin would like to stop that from happening apparently.
Also why am I the only one experiencing this issue if disabling persistence is the issue?
Thanks in advance

**Comment by tbox1911** [comment]
hi, yes 

with persistent = 1;

the server keep ai loaded and they still continue to capture cities/bases.

to prevent this and make the server stop when the last player disconnected, use:

persistent = 0;

in server config

**Comment by tbox1911** [comment]
also, errors like:

13:27:18 Error: Bone propbackpackright doesn't exist in skeleton OFP2_ManSkeleton
13:27:18 Error: Bone propbackpackleft doesn't exist in skeleton OFP2_ManSkeleton
13:27:18 Error: Bone turningaxis doesn't exist in skeleton OFP2_ManSkeleton

and

13:27:19 Warning Message: No entry '.turnSpeed'.
13:27:19 Warning Message: '/' is not a value
13:27:19 Warning Message: No entry '.stance'.
13:27:19 Warning Message: '/' is not a value

often mean you miss some mod on your side
