### ISSUE TITLE
No permission overwrite for special vehicles

### ISSUE THREAD

**Issue by SpaceKoi89p** [tbox1911/Liberation-RX#144]
Can't overwrite the permissions so people who own a special vehicle but have not yet got the rank can use them.

**Comment by tbox1911** [comment]
it's not an issue, it's the purpose of ranking !

use the virtual garage to store vip vehicle, until you have the rank needed

**Comment by MrDj200** [comment]
I'd appreciate a parameter for this as well. 
2000 points is just a bit much for someone who likes to fly jets and only gets time to play once a week or so.
Same with artillery.

Is there some variable or function I can run in the Debug console to let them use it, or is my only option to cheat them to max rank?

**Comment by tbox1911** [comment]
you have a parameters to disable vehicle permission check

search "Enable Vehicles Ownership"

**Comment by MrDj200** [comment]
just tried that. Doesn't work
![image](https://github.com/tbox1911/Liberation-RX/assets/5685500/a0076b3a-d15e-4d9e-b831-e5b5251bb6e7)
![image](https://github.com/tbox1911/Liberation-RX/assets/5685500/57d86c8c-1adf-4ff3-aa96-91c1c1ad5700)

**Comment by tbox1911** [comment]
hi, 
you have a parameters to disable vehicle ownership check
search "Enable Vehicles Ownership"

and another one for Permission check
search "Permissions management"

disable both

**Comment by MrDj200** [comment]
I'll try that the next time we play liberation. We just finished altis yesterday.

You should probably close this ticket, not sure when I'll get the chance to try it
