### ISSUE TITLE
Some zones cannot be captured plus no ennemies are spawning

### ISSUE THREAD

**Issue by EpocDotFr** [tbox1911/Liberation-RX#147]
- Liberation RX version: 1.8.19
- Terrain: Takistan
- Dedicated server: yes
- Server mods: CUP Terrains - Core, CUP Terrains - Maps, CUP Terrains - CWA, CBA_A3, CUP Weapons, CUP Units, CUP Vehicles, CUP Terrains - Maps 2.0, RHSAFRF, RHSUSAF, RHSGREF, RHSSAF, RHSPKL, Advanced Rappelling, Advanced Sling Loading, Advanced Towing, LAMBS_Danger.fsm, LAMBS_Suppression, LAMBS_Turrets, Virolahti - Valtatie 7, ace, ACE Compat - RHS AFRF, ACE Compat - RHS USAF, ACE Compat - RHS: GREF, CUP ACE3 Compatibility Addon - Vehicles, CUP ACE3 Compatibility Addon - Weapons, CUP ACE3 Compatibility Addon - Terrains, ACE Compat - RHS: SAF, LRX_Template

Hi!

For some reason, when playing Liberation RX on Takistan, we aren't able to capture some of the zones, plus there's zero enemies.

It _may_ be linked to this error which _seems_ to happen every time we trigger some OPFOR sectors:

```
12:54:53 Error in expression <selectRandom civilian_boats;
};
};
if (!isNull _classname) then {
_vehicle = cre>
12:54:53   Error position: <isNull _classname) then {
_vehicle = cre>
12:54:53   Error isnull: Type String, expected Object,Group,Script,Config entry,Display (dialog),Control,Network Object,Team member,Task,Diary record,Location
12:54:53 File mpmissions\__cur_mp.Takistan\scripts\shared\functions\F_libSpawnVehicle.sqf..., line 47
```

If it does help, here's the sectors (circled in green) that cannot be captured (we started playing yesterday evening, we did not check all sectors):

![image](https://github.com/tbox1911/Liberation-RX/assets/2053431/5ca38b5e-ca2b-4b12-9d87-0e7033369a2e)

Regarding radio tower 017014 (leftmost green circle), we destroyed the tower to the ground, it however did not allowed us to capture the zone.

**Comment by tbox1911** [comment]
hi,
thanks fro the feedback, I'll fix it asap

**Comment by EpocDotFr** [comment]
I guess #113519f76ca0d27de3c943fc6560d294e429a67f fixed this issue as well?

**Comment by tbox1911** [comment]
I hope so :)

**Comment by EpocDotFr** [comment]
Will test very soon, I'll keep you updated.

**Comment by EpocDotFr** [comment]
Thanks mate, fixed ;)
