### ISSUE TITLE
Some side missions cannot be initialized

### ISSUE THREAD

**Issue by EpocDotFr** [tbox1911/Liberation-RX#148]
- Liberation RX version: 1.8.19
- Terrain: Takistan
- Dedicated server: yes
- Server mods: CUP Terrains - Core, CUP Terrains - Maps, CUP Terrains - CWA, CBA_A3, CUP Weapons, CUP Units, CUP Vehicles, CUP Terrains - Maps 2.0, RHSAFRF, RHSUSAF, RHSGREF, RHSSAF, RHSPKL, Advanced Rappelling, Advanced Sling Loading, Advanced Towing, LAMBS_Danger.fsm, LAMBS_Suppression, LAMBS_Turrets, Virolahti - Valtatie 7, ace, ACE Compat - RHS AFRF, ACE Compat - RHS USAF, ACE Compat - RHS: GREF, CUP ACE3 Compatibility Addon - Vehicles, CUP ACE3 Compatibility Addon - Weapons, CUP ACE3 Compatibility Addon - Terrains, ACE Compat - RHS: SAF, LRX_Template

Hi again!

Some side missions cannot be initialized, namely the Capture VIP one:

```
12:53:00 "--- LRX Error: side mission VIP, cannot find spawn"
12:53:00 "--- LRX Error: A3W Side Mission2 failed to setup: Capture VIP"
```

This results by a message "Next objective" in-game but the next line is empty (this last should display the side mission name).

**Comment by EpocDotFr** [comment]
This issue has not been resolved.

**Comment by EpocDotFr** [comment]
There's indeed only one side mission (mission VIP) failing to initialize, but are you sure this is expected behavior?

```
12:53:00 "--- LRX Error: side mission VIP, cannot find spawn"
12:53:00 "--- LRX Error: A3W Side Mission2 failed to setup: Capture VIP"
```

**Comment by tbox1911** [comment]
maybe there is a specific bug with the VIP

I'll double check start condition :)

**Comment by EpocDotFr** [comment]
Not something blocking btw ;)

**Comment by EpocDotFr** [comment]
Could you reopen this issue as it's not fixed yet?

**Comment by EpocDotFr** [comment]
```
21:34:27 Error in expression <etText (configFile >> "CfgVehicles" >> (_vehicleClass param [0,""]) >> "picture">
21:34:27   Error position: <_vehicleClass param [0,""]) >> "picture">
21:34:27   Error Undefined variable in expression: _vehicleclass
21:34:27 File mpmissions\__cur_mp.Malden\scripts\server\a3w\missions\sideMissions\mission_CaptureVIP.sqf..., line 93
```

Still bugged.

**Comment by tbox1911** [comment]
hi, thanks a lot, I'll fix the classname !
