### ISSUE TITLE
opforcap error

### ISSUE THREAD

**Issue by EpocDotFr** [tbox1911/Liberation-RX#150]
- Liberation RX version: 1.8.26
- Terrain: Takistan
- Dedicated server: yes
- Server mods: CUP Terrains - Core, CUP Terrains - Maps, CUP Terrains - CWA, CBA_A3, CUP Weapons, CUP Units, CUP Vehicles, CUP Terrains - Maps 2.0, RHSAFRF, RHSUSAF, RHSGREF, RHSSAF, RHSPKL, Advanced Rappelling, Advanced Sling Loading, Advanced Towing, LAMBS_Danger.fsm, LAMBS_Suppression, LAMBS_Turrets, Virolahti - Valtatie 7, ace, ACE Compat - RHS AFRF, ACE Compat - RHS USAF, ACE Compat - RHS: GREF, CUP ACE3 Compatibility Addon - Vehicles, CUP ACE3 Compatibility Addon - Weapons, CUP ACE3 Compatibility Addon - Terrains, ACE Compat - RHS: SAF, LRX_Template

Hi again!

I don't know if this has an impact on the game (just tested the mission on two different area - after a player reported the mission has issue since last update - had no issue), but there's new errors:

```
22:12:23 "--- LRX Load Game finish at 6.261"
22:12:23 Error in expression <0 ) ) / 100.0 ,
_units_civ, _units_blu, opforcap,
[time/3600,"HH:MM:SS"] call BI>
22:12:23   Error position: <opforcap,
[time/3600,"HH:MM:SS"] call BI>
22:12:23   Error Undefined variable in expression: opforcap
22:12:23 File mpmissions\__cur_mp.Takistan\scripts\server\offloading\show_fps.sqf..., line 53
```

**Comment by tbox1911** [comment]
hi, thanks for feedback, I'll check

**Comment by EpocDotFr** [comment]
Players are reporting the mission is crashing at a certain point. I do not have any details yet, will check logs later this day.
