### ISSUE TITLE
MOD Present only showing vanilla factions when CUP is loaded

### ISSUE THREAD

**Issue by G-Butter** [tbox1911/Liberation-RX#151]
Hi, when I start this mission from a dedicated server with CUP loaded, the CUP factions do not show up in the MOD preset for either BLUFOR or OPFOR. Do I need to change presets and pack my own PBO file from source or will it be auto detected?

**Comment by tbox1911** [comment]
Hi, you need the LRX_Template mod,
Loaded on client and server
It add support for cup,RHS,etc
