### ISSUE TITLE
Mission fails right after starting

### ISSUE THREAD

**Issue by AngelKing86** [tbox1911/Liberation-RX#153]
We have a massive problem. We modified the fractions for BWMod, and after starting, we encounter ‘Liberation-RX’, resulting in mission failure.
We’ve already reset the savegames, but with no success.

We've also tried it with a different faction or just with different mission parameters. Either we just stand on an island or everyone gets a black screen.

RPA LOG:
16:52:34 [CBA] (xeh) INFO: [13898,200.118,0] PreInit started. v3.16.1.231025
16:52:34 [CBA] (settings) INFO: Reading settings from settings file.
16:52:34 [CBA] (settings) INFO: Finished reading settings from settings file.
16:52:34 [CBA] (settings) INFO: Mission Config: File [cba_settings.sqf] loaded successfully.
16:52:35 [CBA-XEH] old SLX_XEH_COMPILE macro used on \LAxemann\L_Align\addons\Align_sys\functions\fnc_camShake.sqf
16:52:35 [CBA-XEH] old SLX_XEH_COMPILE macro used on \LAxemann\L_Align\addons\Align_sys\functions\fnc_checkContinue.sqf
16:52:35 [CBA] (xeh) WARNING: One or more children of class Air do not support Extended Event Handlers. Fall back to loop.
16:52:35 Wrong location draw style - "ACRE_RequiredDrawStyle"
16:52:35 [ACE] (common) INFO: Parsed Settings Configs [0.0 ms]
16:52:36 [CBA] (xeh) INFO: [13898,201.675,0] PreInit finished.
16:52:36 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:36 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:36 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:36 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:37 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:37 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:37 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:37 PortableHelipadLight_01_blue_F: light_1_blinking - unknown animation source MarkerLight (defined in AnimationSources::Light_1_source)
16:52:37 "--- Liberation RX by pSiKO ---"
16:52:37 "version v2.0.14 build - date: 01/03/2024"
16:52:37 "--- Init start ---"
16:52:37 Error: Object(2 : 51) not found
16:52:37 Error: Object(2 : 52) not found
16:52:37 Error: Object(2 : 53) not found
16:52:37 Error: Object(2 : 54) not found
16:52:37 Error: Object(2 : 61) not found
16:52:37 Error: Object(2 : 62) not found
16:52:37 Error: Object(2 : 63) not found
16:52:37 Error: Object(2 : 64) not found
16:52:37 Error: Object(2 : 69) not found
16:52:37 Error: Object(2 : 70) not found
16:52:37 Error: Object(2 : 71) not found
16:52:37 Error: Object(2 : 72) not found
16:52:37 Error: Object(2 : 73) not found
16:52:37 Error: Object(2 : 74) not found
16:52:37 Error: Object(2 : 75) not found
16:52:37 Error: Object(2 : 76) not found
16:52:37 d:\bis\source\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
16:52:37 "--- LRX Mod Detection: BW_BLU vs A3_OPF_PAC"
16:52:37 Loading movesType CfgMovesDog_F
16:52:37 Reading cached action map data
16:52:37 Attempt to override final function - bis_fnc_storeparamsvalues_data
16:52:38 "Advanced Urban Rappelling Loading..."
16:52:38 "Advanced Urban Rappelling Loaded"
16:52:38 "Advanced Sling Loading Loading..."
16:52:38 "Advanced Sling Loading Loaded"
16:52:38 "Advanced Towing Loading..."
16:52:38 "Advanced Towing Loaded"
16:52:38 [CBA] (xeh) INFO: [13917,204.145,0] PostInit started. MISSIONINIT: missionName=Liberation_RX_BW, missionVersion=54, worldName=Tanoa, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false
16:52:39 Attempt to override final function - l_suppress_suppress_sys_fnc_fired
16:52:39 [CBA] (versioning) INFO: [13917,204.319,0] VERSIONING:cba=3.16.1.231025, zen=1.14.0.34, ace=3.16.3.79, bwa3=2.6, acre=2.12.0.1056, pzpl=0.1.3.3
16:52:39 [ACE] (common) INFO: Updating ACE from [] to [3.16.3.79]
16:52:39 [ACE] (common) INFO: ACE is version 3.16.3.79 - CBA is version 3.16.1.231025 (min required 3.16.0)
16:52:39 [CBA] (xeh) INFO: [13917,204.762,0] PostInit finished.
16:52:39 [ACRE] (sys_signal) INFO: Using radio propagation model: LOS Multipath
16:52:39 [ACE] (common) INFO: Settings initialized.
16:52:39 [ACE] (common) INFO: 24 delayed functions running.
16:52:39 "VCOM: Loaded Default Settings"
16:52:57 Server: Object 0:0 not found (message Type_185)
16:53:00 [ACRE] (sys_data) INFO: Data Sync for acre_player: [2:492,4]
16:53:00  Mission id: dc160f79dca1288d42a032bc639614fbb1b4d9cc
16:53:00 Error: Object(4 : 4) not found
16:53:00 Warning Message: Sound jump_sfx not found
16:53:00 Warning Message: Sound jump_sfx not found
16:53:00 Warning Message: Sound land_2 not found
16:53:00 Warning Message: Sound land_2 not found
16:53:01 soldier[BWA3_RiflemanAT_PzF3_Fleck]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:01 soldier[BWA3_RiflemanAT_PzF3_Fleck]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:01 "VCOM: Loaded CBA settings"
16:53:01 "VCOM: Loaded CBA settings"
16:53:02 soldier[BWA3_MachineGunner_MG3_Fleck]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:02 warning: entry "specular' size 4, expected 4
16:53:02 soldier[BWA3_RiflemanAA_Fliegerfaust_Fleck]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:02 soldier[BWA3_RiflemanAA_Fliegerfaust_Fleck]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:02 soldier[B_W_Soldier_LAT2_F]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:02 soldier[B_W_Soldier_LAT2_F]:Some of magazines weren't stored in soldier Vest or Uniform?
16:53:03 SelectionID "31" is wrong for shape "bwa3_uniforms\bwa3_uniform_crew.p3d"
16:53:03 SelectionID "32" is wrong for shape "bwa3_uniforms\bwa3_uniform_crew.p3d"
16:53:03 SelectionID "31" is wrong for shape "bwa3_uniforms\bwa3_uniform_crew.p3d"
16:53:03 SelectionID "32" is wrong for shape "bwa3_uniforms\bwa3_uniform_crew.p3d"
16:53:04 "--- LRX World: Tanoa - Auto-Name failed for marker: factory_5"
16:53:04 "--- Init stop ---"
16:53:04 "--- Server Init start ---"
16:53:05 "--- LRX Starting Civilian Manager"
16:53:05 "--- LRX Starting Patrols Manager"
16:53:05 "--- LRX Weather changed to 0.2 - rain 0 - fog 0 - wind 2/3"
16:53:05 "--- LRX Advanced Rappelling Initialized"
16:53:08 "--- Server Init stop ---"
16:53:08 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:53:08 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:53:08 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:53:08 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:53:13 "--- LRX Cleanup player "
16:53:13 "--- LRX MP Warmup (no save done), 287sec remaining..."
16:53:13 "--- LRX Mission End!"
16:53:13 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:13 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:14 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:15 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.
16:53:15 Warning: Adding units to a remote group is not safe. Please use setGroupOwner to change the group owner first.

**Comment by tbox1911** [comment]
try to clear mission settings (in parameters)

**Comment by tbox1911** [comment]
yep, send me the pbo

**Comment by tbox1911** [comment]
ok, I'll check
I tell you

**Comment by tbox1911** [comment]
I'll try your pbo on my dedicated, and it's work
maybe there an error in server config ?

can you share the server.cfg and the server.rpt files ?

**Comment by tbox1911** [comment]
hi,
in the log I see the mission startup
`21:41:31 "--- Init stop ---"
21:41:31 "--- Server Init start ---"
21:41:32 "--- LRX Weather changed to 0.14 - rain 0 - fog 0 - wind 3/0"
21:41:32 "--- LRX Starting Patrols Manager"
21:41:32 "--- LRX Starting Civilian Manager"
21:41:33 "--- LRX Advanced Rappelling Initialized"
21:41:36 "--- Server Init stop ---"
<LRX server started>

<user quit>
21:41:41 "--- LRX Cleanup player AngelKing86 ()"
21:41:41 "--- LRX MP Warmup (no save done), 285sec remaining..."
21:41:41 "--- LRX Mission End!"`

you should wait a bit more before quitting, (max 1min)

all script errors come from other mod
you could try with less mod ? (droggo)

come to our Discord to see mod conflict page
https://discord.gg/wgg9DkHt

my advice: start your mission with **only** needed mod (faction BW_BLU), no more.
and retry, maybe reset config and wipe save (in lobby parameters)
it should work.

then add your mod 3 by 3 until you find the incompatible mod.
