### ISSUE TITLE
XML Stringtable.XML Reference to an undeclared entry

### ISSUE THREAD

**Issue by Alfred-Neuman** [tbox1911/Liberation-RX#157]
Version de tabler : 0.9.1.0
Last file xml

I've created a PR https://github.com/tbox1911/Liberation-RX/pull/156 for an error on the same file.

tabler cannot open the stringtable.xml file
`Reference to an undeclared entry, 'LT' , Line 7391, position 47.`

The line in question 
https://github.com/tbox1911/Liberation-RX/blob/62f50fff39306f88106b915335e4bebf971d0d67/core.liberation/stringtable.xml#L7391

**Comment by tbox1911** [comment]
hi thank you,
 I've merged PR#156
 
 I think the error come from the LT uppercase.
 I fix it

**Comment by Alfred-Neuman** [comment]
hi
new error

![image](https://github.com/tbox1911/Liberation-RX/assets/130893962/07589c5a-40ea-4af8-b6bd-f160dfdd0461)

duplicate key
name: `Original`
entry `STR_TUTO_TEXT5`
https://github.com/Alfred-Neuman/Liberation-RX/blob/5f1e168e2f2a99b6504f686ab4aae6f7f37a06af/core.liberation/stringtable.xml#L3983

There are two text entries with `Original` tags

l3984-3991 
https://github.com/Alfred-Neuman/Liberation-RX/blob/5f1e168e2f2a99b6504f686ab4aae6f7f37a06af/core.liberation/stringtable.xml#L3984C1-L3991C15

and l4016-4023
https://github.com/Alfred-Neuman/Liberation-RX/blob/5f1e168e2f2a99b6504f686ab4aae6f7f37a06af/core.liberation/stringtable.xml#L4016-L4023

Solution: rename or delete

**Comment by tbox1911** [comment]
Thanks a lot for reporting,
I'll fix them asap!

**Comment by tbox1911** [comment]
merged
