### ISSUE TITLE
Double Marksman infantry unit in the Build Menu, missing AutoRifleman

### ISSUE THREAD

**Issue by PetrusMaximus0** [tbox1911/Liberation-RX#159]
While using the Bluefor Pacific loadout, there is no option to recruit an Autorifleman, but there are two options for Marksman. 

I can trace the issue to this line of the code.

https://github.com/tbox1911/Liberation-RX/blob/ad9e7303575ed17596f03415bcbb6d0229195e5f/core.liberation/mod_template/A3_BLU_PAC/classnames_west.sqf#L32

Changing the aforementioned line to ["B_T_soldier_AR_F",1,30,0,GRLIB_perm_inf] fixes the issue for me, but I thought it would be useful to mention here.

**Comment by tbox1911** [comment]
thanks for the fix,I'll update the mod soon
