### ISSUE TITLE
Info signs explanation request

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#16]
Could you, please, add some explanation about the signs to Tutorial or to Diary
![1609960238827.jpg.png](https://user-images.githubusercontent.com/7004992/103810273-a4b14f00-5063-11eb-8f3d-4a3746367ac8.png)
Newcomers always ask and not always someone present who can explain. Thanks.

**Comment by tbox1911** [comment]
you're right , I need to improve the tutorial

added to todo list ;)
