### ISSUE TITLE
Missing Sidebar and welcome message when entering game

### ISSUE THREAD

**Issue by ThornbirdSitcom** [tbox1911/Liberation-RX#160]
Since v2.4.4, there's no more sidebar to show vault and welcome message.
Only tested on Takistan.
![B6IG1()M9MCW$WY2M71I1E4](https://github.com/user-attachments/assets/fbd3fa02-3941-4539-b068-7cdc75cf2e0e)

**Comment by tbox1911** [comment]
hi, 
can you send me the server.rpt (log file) please.
I'll check it

also, if you are using external mod, please retry without **any** mods. 
just to be sure the issue come from the mission itself and not from a mod .

**Comment by ThornbirdSitcom** [comment]
Hi.
I attached 2 rpt files here.
One in v2.4.5(Arma3_x64_2024-07-23_11-29-26.rpt) and the other in v2.4.2(Arma3_x64_2024-07-23_13-53-14.rpt) as reference. This problem occurs only in v2.4.4 and v2.4.5, which means in v2.4.3 and v2.4.2, everything seems alright.
The mods was cut to the bone - only map mod loaded.

Hopefully these will help. :)[Arma3 rpts.zip](https://github.com/user-attachments/files/16365949/Arma3.rpts.zip)

**Comment by tbox1911** [comment]
there is nothing wrong on server side,
try to wipe savegame (make a backup if needed)
AND clear/reset settings

feel free to come on our Discord server, could be helpful to investigate
https://discord.gg/B9J9KbQP

**Comment by tbox1911** [comment]
ok, I'm able to reproduce the issue here,

you can expect a bugfix soon :)

**Comment by ThornbirdSitcom** [comment]
Checked. Bug fixed in v2.4.7.
Sincerely appreciate for your quick response and hard work on this mission! Thank you!
