### ISSUE TITLE
Side mission "Enemy Helicopter" triggered wrongly when finished [ACE environment]

### ISSUE THREAD

**Issue by ThornbirdSitcom** [tbox1911/Liberation-RX#161]
In ACE environment, the side mission "Enemy Helicopter" always ends with "mission failed" when the target helicopter is down.
The side mission is recorded in rpt from appr. line 2278 to line 2343, during which the helicopter is hit by my stinger. It looks little information but I'll attach the rpt here.
In normal environment this side mission works well. 
Arma3_x64_2024-07-27_11-29-43.rpt is in ACE environment while Arma3_x64_2024-07-27_11-37-02.rpt is in Vanilla.
 
[Arma3 rpts.zip](https://github.com/user-attachments/files/16399073/Arma3.rpts.zip)

**Comment by tbox1911** [comment]
hi,

ACE  is a game in the game!

thank for all info, I'll check why.
this bug should impact others parts in the mission

**Comment by tbox1911** [comment]
hi, I can't reproduce the issue here, with only ace loaded.

btw, in your log I see:

11:30:37 Missing addons detected:
11:30:37   real_uniform_unlock
11:30:37   kat_misc

also retry without
- Achilles (1.3.1)
- Zeus Enhanced - ACE3 Compatibility
- Zeus Enhanced 1.14.0

**Comment by ThornbirdSitcom** [comment]
Hi, I've checked that addons and loaded only ace and map mod and ran in non-edited mission. Sadly this bug occured again.

Is there anything I can help from my side?( For example, add some extra log command somewhere)

I'll try in other maps to see whether it happens again.

Sorry for the late reply. I'm crazily occupied recently TAT

**Comment by ThornbirdSitcom** [comment]
[Arma3_x64_2024-08-02_08-01-45.zip](https://github.com/user-attachments/files/16467108/Arma3_x64_2024-08-02_08-01-45.zip)
BTW this is the rpt I tried today. Thanks for your patience!

**Comment by ThornbirdSitcom** [comment]
Hi,

I tried with only CBA and ace3 at Malden. Sadly this bug triggered again.

There's something interesting: the side mission is shown failed, but at chat bar the console hint that I destroyed the helichopter.

The RPT is attached below. Thanks for your patience!

[Arma3_x64_2024-08-02_08-55-21.zip](https://github.com/user-attachments/files/16467658/Arma3_x64_2024-08-02_08-55-21.zip)

**Comment by tbox1911** [comment]
hi, strange !
just to be sure,
is it working when you just start the mission alone (with no mod at all) ?
I'll check for ace incompatibility 
and I review the success/failure condition

**Comment by ThornbirdSitcom** [comment]
Hi, 

I tried only for once in Vanilla but at that time, the mission finishes with success. 
I'll try further later, and test even on dedicated server. 
Feel free to leave whatever I may help, I'll try as I can.

**Comment by ThornbirdSitcom** [comment]
Alas, I tried once in Vanilla but this time mission failed again.
I'll continue trying so

**Comment by tbox1911** [comment]
in vanilla setup, the mission work, for sure!
several players reported ok in Discord
 
btw, I prepare an update that can fix some mission issue

**Comment by ThornbirdSitcom** [comment]
I tried several times locally, most of which failed.
Maybe it's the problem only happens locally. I'll try dedicated server later.
Anyway thanks for your patience! I'll update what I find ASAP

**Comment by tbox1911** [comment]
hi,
try with latest v2.4.10

**Comment by ThornbirdSitcom** [comment]
Hi,

Thanks for notification! Unfortunately I'm crazily occupied since last week, but it should be ended next week. I'll update it and see what I can find then.

Again, sincere thanks to everything you made to this project!

**Comment by ThornbirdSitcom** [comment]
Hi,

I uploaded it to the dedicated server and it seems work alright recently. I guess it should be solved.

I'll close this issue right now, and if any accident happen I'll try to report with more info.

Sorry for the late reply. I just make myself free from heavy work recently! And again, thank you for your patience and help!
