### ISSUE TITLE
Unable To Respawn[ACE]

### ISSUE THREAD

**Issue by jishnukarri** [tbox1911/Liberation-RX#162]
I been running [Liberation_RX.Altis.pbo](https://github.com/tbox1911/Liberation-RX/releases/download/v2.4.8/Liberation_RX.Altis.pbo) on a dedicated server.
The fatigue system doesn't work so I added ```player enablefatigue false;``` in the ```onPlayerRespawn.sqf```
Now that I added this the respawn system breaks it doesn't even work
you get to base but not to FOBs

[Current Mission File](https://file.io/Mskx97W2kUvM)

**Comment by tbox1911** [comment]
the LRX fatigue/stamina parameters is working, 
it's  just ACE that overwrite/use it's own code to manage fatigue

look on ace parameters
