### ISSUE TITLE
FOB spawns below ground after server or mission restart

### ISSUE THREAD

**Issue by ericrybick** [tbox1911/Liberation-RX#163]
Hi, we are currently facing the issue that the FOB spawns below the ground after restarting the mission or server. This also leads to players spawning on the northern small island. It started happening after relocating the FOB the second time. We are playing on Tanoa if that matters.

**Comment by tbox1911** [comment]
I cannot reproduce this issue,
did you use external mod ?
(and share the serve rpt file, please)

**Comment by ericrybick** [comment]
Hello again, I checked the rpt file and found many errors related to other mods. After fixing those, the issues with the FOB were gone. Sorry for wasting your time. I didn't know about the rpt logs before... Lesson learned, thanks!

**Comment by tbox1911** [comment]
you're welcome friend !
if you have other issue/questions, visit us at our Discord
 https://discord.gg/TZSw7mBZ
