### ISSUE TITLE
infinite loading of "Building the Arsenal" !

### ISSUE THREAD

**Issue by OfficialMikeJ** [tbox1911/Liberation-RX#164]
I am trying to test this build of Liberation. every time I go to load it everything else loads just fine but it's sitting or stuck on "Building the arsenal". I leave it for 5-10 minutes still no progress. 

I have a sloth of mods loaded but not sure why it's not working ?.

Thanks.

**Comment by logimy** [comment]
I believe this is the reason
![image](https://github.com/user-attachments/assets/6f2d4b24-919f-4c91-8792-362ff4ea0bc3)

If "GRLIB_ACE_enabled" then LARs_arsenal_Liberation_cargo is never created and user get stuck in infinite loading screen.

**Comment by tbox1911** [comment]
thanks for the input, I'll take a look :)
