### ISSUE TITLE
Hello great guy

### ISSUE THREAD

**Issue by Maciccio** [tbox1911/Liberation-RX#173]
Can I disable revive for all AI (including the doctor), and enable it only for players?
If it's not in the config parameters, can I edit a file?

**Comment by tbox1911** [comment]
hello,

you mean only the AI can revive the player, but they can't revive each others ?
or 
only the player can revive the AI ?

you can choose "only medic can revive" and select medic class for you, 
and use anything else for your AI

**Comment by Maciccio** [comment]
I wish only players could revive other players. And no AI, it can't revive anyone

**Comment by tbox1911** [comment]
I see, actually it's not possible.
I'll try to see if I can add a such parameter
