### ISSUE TITLE
Players reporting Convoy hijack mission bug

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#18]
Hi.
My players reporting a Convoy hijack bug. Convoy stops in a city and don't moves on a route.

**Comment by tbox1911** [comment]
yes, I know the convoy path finding is way bogged !

unit use waypoint to move (AI find path themself), but sometime (too often) they stuck in vehicle or building and stop.
waypoints are still active but unit wont move

I don't know if I can do something about this

I gonna look

**Comment by Varrkan82** [comment]
Not a mission bug
