### ISSUE TITLE
Banned for TK player can not be unbanned via Admin menu as it is not appeared there

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#19]
If player been banned for TK he can not join and can not be unbanned as before he is not joined the game he not appeared in players menu to be unbanned in Admin menu

**Comment by tbox1911** [comment]
hi,

the banned player must be connected to mission lobby to be unbanned !

**Comment by Varrkan82** [comment]
> hi,
> 
> the banned player must be connected to mission lobby to be unbanned !

I've tried. Peter not appeared in a list to be unbanned.

**Comment by tbox1911** [comment]
I see, he must try to connect and in the same time you have to open the admin menu and unban him

not very convenient; I'll try to upgrade this

**Comment by Varrkan82** [comment]
> I see, he must try to connect and in the same time you have to open the admin menu and unban him
> 
> not very convenient; I'll try to upgrade this

Too hard to catch the same moment as a kick action happened much faster than I'm clicking mouse... 😁

**Comment by Varrkan82** [comment]
@tbox1911 I'm propose to change a TK logic.
For each TK user should pay a some amount of Ammo (500 for example). If he hasn't enough Ammo to pay for TK - he should be banned. But an unban process, surely should be a little easier than now :) 
This logic will cut a newcomers which will kill a teammates but can give a chance for other players to be not banned for accident team kill if they are playing well and enough of time to gain some resources.

**Comment by tbox1911** [comment]
i push a patch that change unban
now list come from internal source of banned player
+ can unban offline player
- cannot show their name
- selection is by UID

**Comment by Varrkan82** [comment]
Guys claimed me about a 500 Ammo penalty. Decreased to 100 in my version. Player told me it cuts an Ammo even if people injured with a vehicle if they jupms under the wheels by themselves. Damned suiciders...
