### ISSUE TITLE
Please, increase enemy spawn radius on points-of-interest

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#20]
Please, increase an enemy spawn radius as they are not spawned while someone goes into a round zone. But it makes impossible any recon ops or sniper job on a long ranges.

**Comment by Varrkan82** [comment]
Maybe it could be not all of enemies, but vehicles and a half of infantries.

**Comment by Varrkan82** [comment]
We've discussed this behaviour with my players... This could significantly decrease server performance. Need to analyse it more accurate. At least about how it could be done if a player flying througt above the point...

**Comment by tbox1911** [comment]
the radius for zone being active, can be configured in "gameplay_constants.sqf" depending on the map
GRLIB_sector_size (on altis 600, on startis 400)
(we have to make a choice to not enable all the zone on the map!)

make it bigger if you want, but as you notice this will significantly decrease server performance !

to 'activate' a zone for far than GRLIB_sector_size, you can use uav or any unit that go inside the zone radius.
only aircraft cannot capture a zone, must be solider on ground
