### ISSUE TITLE
TK penalty applied to any hit to other player

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#21]
As I understand - the penalty should be applied only if a injured player become incapacitated. But now it is applied to any hit to other player. Ine hit -500 ammo. Few hits and you have no ammo at all.

**Comment by tbox1911** [comment]
not exactly:

TK/Penalty occur on the first damage from an human to another human.

500 is too much, lower to 200

**Comment by Varrkan82** [comment]
> not exactly:
> 
> TK/Penalty occur on the first damage from an human to another human.
> 
> 500 is too much, lower to 200

I know - this is not an issue exactly, but maybe it is better to change the logic to apply penalty not to a damage, but to kill exactly? When the damaged player become unconscious.

**Comment by tbox1911** [comment]
i see, but the idea behind tk protect, is to avoid the player to be damaged or unconscious... 
so I can't wait for 'player is wounded', only  'is player has receive damage'

we can found a better logic ! :)
