### ISSUE TITLE
Function error after joining appeared on the screen

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#22]
![image](https://user-images.githubusercontent.com/7004992/104126157-a9c41600-5363-11eb-869f-9815a9b1bed6.png)

**Comment by tbox1911** [comment]
you found in C:\Users\<YourName>\AppData\Local\Arma 3

the rpt file (text)  please send me the whole block containing the error

**Comment by Varrkan82** [comment]
Will try to find this log file.

**Comment by Varrkan82** [comment]
Here is a log file

[Arma3_x64_2021-01-10_16-40-15.zip](https://github.com/tbox1911/Liberation-RX/files/5798809/Arma3_x64_2021-01-10_16-40-15.zip)

**Comment by tbox1911** [comment]
i read the log file, 
and I think it's because wildlife look for "sectors_allsectors" before it was initialized

should be fixed in 45d54eb4638dd82609b4398e3df824d82597c41f

**Comment by Varrkan82** [comment]
Looks fixed for me.
