### ISSUE TITLE
Renamed Units Are Not Retaining Their New Names

### ISSUE THREAD

**Issue by gkleinfe** [tbox1911/Liberation-RX#25]
Ranaming is working for the currently logged in session only.  If I rename units, log out then back in, they revert to previous names and don't keep their new names.

**Comment by tbox1911** [comment]
yes, I know, it's the default behaviour,
the renaming option it's a temporary 'hack' (during a game session) 
there is no way to keep the user defined name after player disconnect .

sad but true !
