### ISSUE TITLE
Feature request. Add action menu for damaged player to take action about TK

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#27]
I was running one another mission, Invade & Annex from Quiksilver. It has its own protection system called Robocop. And if TK happened, damaged player see a message from Robocop with an options to pay mercy to damager or to punish him. After a few punishments player will kicked out. Maybe you will provide something like that to you TK protection? It will avoid kick for a many players if a damaged player has no pretension to damager for a damage, also it will avoid an extra payments from damager for each damage.

**Comment by tbox1911** [comment]
can think about this :)

**Comment by tbox1911** [comment]
At first my TK system was close to that, it ask for Punish or Forgive.
but , in game, that broke the gameplay. (suddenly a question windows pop up!)

I think the actual logic (pay fine or take ban ticket, above 4 tickets you'll be banned) is a valid compromise.

the fine amount and the number of ticket can be configured is easily in "tk_init.sqf"
and the admin can unban.

"if a damaged player has no pretension to damager"  very, very hard to code ;)

The main purpose of this protection is to kick quickly the players that shoot everything without caution.
if you have some hours of game, you have enough money to 'afford' an accidental TK.

the same logic applies to civilian and friendly units.

and keep sending me your ideas for improvement :) !

**Comment by Varrkan82** [comment]
It is should not be a pop-up exactly, in I&A its adds an extra-optiins to action menu and information pop-up about possibility to use it. Damaged player should to scroll and select one. If he will not select for an amount of time (don't remember, something around a 15 seconds) - this scroll action removed and damager will mercy automatically.

**Comment by tbox1911** [comment]
I can add server params to choose (2 dropdown list)

- strict mode:
  (3 warning then auto ban) for public server
   no more fine

- relax mode:
  ask for player to Punish or Forgive (last for 1 minue)
  if offender receive more than 3 punish, it will be ban

- the number of warning will be in server param too

**Comment by Varrkan82** [comment]
> I can add server params to choose (2 dropdown list)
> 
> * strict mode: (default)
>   (3 warning then auto ban) for public server
>   no more fine
> * relax mode:
>   ask for player to Punish or Forgive (last for 1 minute)
>   if offender receive more than 3 punish, it will be ban
> * the number of warning will be in server param too

That would be greate! Thanks!

**Comment by tbox1911** [comment]
try latest build :)

**Comment by Varrkan82** [comment]
> try latest build :)

Thank you again! I'll merge your changes and setup this version to my server ASAP. Maybe tomorrow evening. Unfortunately can't check it by myself, I'm far away from my Windows PC for a two next weeks. I'll report you any issues what my players possibly find.

**Comment by Varrkan82** [comment]
No issues reported from my players, so I suppose - there is all fine. Thank you.
