### ISSUE TITLE
Side missions are disaprearing after a some time

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#3]
Hi.
I'm not sure this is not a planned behavior, but my players reported me about a Side missions are disapearing from the map after a some time passsing. Their selection become inactive and it is still inactive till the server restart. Could it be fixed if this is a bug? 
Thank you.

**Comment by tbox1911** [comment]
hi Vitalii,

about the side missions:

two type:

temporary  (disappear if not done after 45min)
  - aircraft wreck, hostile helicopter, resistance etc..


semi permanent (must be terminated)
- fob hunting, attack convoy, etc

  you have to fully terminate these kind of mission
  bring back to fob prisoners/pilots
  destroy convoy /recycle ammobox


which is the name of the mission that do not end correctly ?

**Comment by Varrkan82** [comment]
Yes, this all you called a temporary. Which are marked with a big red cross in the map.
![These](https://user-images.githubusercontent.com/7004992/78147413-2375bd80-743c-11ea-8195-b2dc37156b1b.jpg)

**Comment by tbox1911** [comment]
Hi,

these kind of missions will run for 45minutes, unless completed then should
disappear.
every 30 minutes a random side mission should sart

I've push an update on github
to fix a performance issue and fix some others bug

please update your pbo

keep me in touch

Good Game !

**Comment by Varrkan82** [comment]
>please update your pbo
This is not so easy... :) I've changed all Russian strings in stringtable.xml to Ukrainian and translated an all English text through the all mission files. So I'm updating by merging an all files manually, one by one. And it's is much easier for me to do that periodically with a batch of updates.

But thank you any way for your job!

**Comment by tbox1911** [comment]
no problem!
the mission is ok to modding, you just have few files to keep.

stringtable.xml
gameplay_constants.sqf
mission.sqm
fixed_position.sqf (optional to set static marker)
whitelist.sqf (optional to define white list admin)

please take a look at :https://github.com/tbox1911/Liberation-RX
you see how its work


I can help if you need :)

wash your hand ! :p

**Comment by Varrkan82** [comment]
Thank you. It's already translated and running at [UA]Arma 3 Ukraine Liberation server. Fill free too join and check. All your credentials are saved. Of cause there could be some untranslated objects... I've translated a Russian strings in stringtable.xml as Arma not support Ukrainian from sketch.
