### ISSUE TITLE
TK Relax mode issue

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#30]
Guys tested: one shooting to another, the third one is punished. :)
Also - it is possible to punish twice for a single shot!
Also - is it possible for an each punishment to decrease a punished player's Ammo amount for a some amount (-5 Ammo for example)?
Also - one player reported about there is no damage while shooting to a teammate. Looks like a a damage is switched off at all.

Could you check, please? Also fill free to join and check yourselves (178.15zero.80.nine1:2302).

**Comment by tbox1911** [comment]
strange ! look the like relax mode is not enable...
the only way a player can be kick in relax mod, is to be punished by player 4 (or more) times

-  damage is switched off
 yep cannot be killed by tk. (only a light wound)

-  it is possible to punish twice for a single shot
nope

- (..) fine (..) 
nope (too much code for so little)

i test here with 2 pc, and it seems to work fine

**Comment by Varrkan82** [comment]
> strange ! look the like relax mode is not enable...
> the only way a player can be kick in relax mod, is to be punished by player 4 (or more) times
> 
> * damage is switched off
>   yep cannot be killed by tk. (only a light wound)
> * it is possible to punish twice for a single shot
>   nope
> * (..) fine (..)
>   nope (too much code for so little)
> 
> i test here with 2 pc, and it seems to work fine

OK, I'll ask guys to retest as I found some un-merged changes. It is too hard to control all of them. I'm revisioning it all from time to time and usually founding something what was missed during a daily syncing.
