### ISSUE TITLE
UAV MQ-4A & A-164 - pylons can not be changed (SDB_DALE)

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#34]

**Comment by tbox1911** [comment]
note: not all aircraft can be edit via DALE
they must have  "dynamicLoadout"

the A-164 CAS is working, the screenshot from bohemia forum actually show A-164 Wipeout !

(you have to update the classnames.sqf)  "B_Plane_CAS_01_dynamicLoadout_F"

I miss the MQ-4A, i add it !
