### ISSUE TITLE
the mission does not end

### ISSUE THREAD

**Issue by Evaexe117** [tbox1911/Liberation-RX#46]
Hello.

Since i use liberation RX i encounter a problem.
When all city are captures, ( map il full blue ) and there is no enemy left.
The mission will not end and stay in this state.
How its possible to end mission and start the next mission ?

Thanks,.

**Comment by tbox1911** [comment]
hi, 

that strange ! LRX run fine on any other servers (dedicated / hosted)
so I think this part is working.

can you give me more details:

on which island do you play ?
which faction ? (blu/op/ind/cup/cm)
do you use other MOD ?

you can:

- try without other mod
- update with the latest build
- wipe savegame (that reset mission and start a new one)

**Comment by Evaexe117** [comment]
Hi,
Server is hosted on linux.
Here the launcher
`
./arma3server_x64 -autoInit -profiles=serverProfile -config=server.cfg "-mod=@CBA_A3;@CUP Terrains - Core;@CUP Terrains - Maps;@CUP Units;@CUP Vehicles;@CUP Weapons;@Enhanced Movement;@Fallujah V1.2;@Isla Duala;" "-serverMod=@server;@extDB3;"
`

On config server :
`persistent=1;`
is used.

Thanks.

**Comment by tbox1911** [comment]
hi,

LRX don't need an persistent server (continue to run even it's no player)

try without  -autoInit and to set persistent=0;

should work ;)

**Comment by Evaexe117** [comment]
Copy, thanks ! 
i'll close this and re-open if necessary
