### ISSUE TITLE
Support for Sefrou-Ramal terrain

### ISSUE THREAD

**Issue by mplorentz** [tbox1911/Liberation-RX#50]
👋 hi, my friends and I have really been enjoying this mission. Do you have any plans to support the new Sefrou-Ramal map from the Western Sahara DLC?

**Comment by tbox1911** [comment]
hi,

I"m on it :)
Just got the map few days ago !

you can expect a beta version at the end of the of the week

**Comment by mplorentz** [comment]
Awesome! I think we will be finishing up our campaign on Stratis in the next week or two and we could be Guinea pigs for the beta.

**Comment by tbox1911** [comment]
hi, pbo is out (in build folder) 
not yet on steam
i add classname for UNA/FIA

the map is very good

**Comment by mplorentz** [comment]
@tbox1911 thanks! We will give it a try soon.

**Comment by tbox1911** [comment]
mission is out
