### ISSUE TITLE
Enemies spawn too close to players

### ISSUE THREAD

**Issue by mplorentz** [tbox1911/Liberation-RX#56]
We have had a recurring issue where a capture zone isn't "activated" until we are already inside it, and then it ends up spawning enemies all around us. It would be nice to bump up the zone activation radius or make it a configurable parameter like KP liberation.

**Comment by tbox1911** [comment]
the radius to activate a zone is defined in the file gameplay_constants.sqf (one per map)
GRLIB_sector_size = 700;

this value is different for each map

you also have an server option to override this value
- The size of a sector (radius)

maybe the game wait too long before spawning enemy, I'll fix that

**Comment by tbox1911** [comment]
I made some change to speed up the spawn

**Comment by mplorentz** [comment]
Ok we will try it out and report back.

**Comment by mplorentz** [comment]
@tbox1911 this is working much better for us! While we did still see units spawn in at a distance sometimes I think that is to be expected. They didn't spawn around us like they were before.
