### ISSUE TITLE
Vehices are not usable with permissions turned off

### ISSUE THREAD

**Issue by mplorentz** [tbox1911/Liberation-RX#57]
I turned the "Permissions" parameter off in our config file, but it wouldn't let anyone on the server drive any vehicle except the mobile respawn Huron. Even trying to drive a Quad bike would give an error message that you werent allowed to use light vehicles. Gaining some rank points didn't seem to help, but turning Permissions back on fixed it.

**Comment by tbox1911** [comment]
there is two options in server params

- Permissions Management ON/OFF
respect the rank needed to use vehicle

- Enable Vehicles Ownership ON/OFF
respect the actual owner to use vehicle 

if you disable theses 2 options, every one can use any vehicles

**Comment by mplorentz** [comment]
I don't see a param for vehicle ownership in https://github.com/tbox1911/Liberation-RX/blob/master/mission_param.cfg. Does `mission_param.cfg` need updating maybe? We are using a config file to set up our parameters so I copied them from that file.

**Comment by tbox1911** [comment]
you're right I miss to update the config file
I'll do it asap !

**Comment by tbox1911** [comment]
should be ok, in this release
please test

**Comment by mplorentz** [comment]
This is fixed the build from commit `9ab80326`. Thank you!
