### ISSUE TITLE
Question on mod support

### ISSUE THREAD

**Issue by HoomanDiscord** [tbox1911/Liberation-RX#58]
Hey guys, just stumbled upon this and it looks great so far!
I was just wondering if there are any mods that you would recommend or if the mods that I used on kp liberation should also work fine,

**Comment by tbox1911** [comment]
hi, no mod are needed
except for the map :)

all features are coded in the game engine

**Comment by HoomanDiscord** [comment]
Thank you for responding, hope yous do great on your project.
