### ISSUE TITLE
Spawning with truck seems like an oversight.

### ISSUE THREAD

**Issue by HoomanDiscord** [tbox1911/Liberation-RX#59]
Started this up on Altis and noticed that starting with a truck makes you spawn on island you cannot get off of without using a heli which I would like to avoid, is this intended or a simple oversight?

**Comment by tbox1911** [comment]
It's desired !
LRX can be used on a wide variety of maps.

on some maps (which are not islands) you can choose to have a box for the fob and a helicopter, sometimes you will prefer the truck.
for example: Takistan or Livoni

not all mission options are useful on all maps.

if you don't want to use a helicopter to transport the first fob, how do you plan to do it?

**Comment by HoomanDiscord** [comment]
Ah ok, thank you for clarifying, I was just a bit confused on why the option was there if it didn't work.
