### ISSUE TITLE
Hi i haw Problem modyfing/adding new units 

### ISSUE THREAD

**Issue by Spec47** [tbox1911/Liberation-RX#60]
Hi I haw a Problem modifying/adding new units in the class name after the new build sys  Update Before it was easy to add new units from Other mods but after the update, I don't get how to add + new units
can someone help me understand how it has changed and how it works now
thank you

**Comment by tbox1911** [comment]
we have upgraded the classname system, 
you have more choice to customize the mission and adding new units

please come on our discord to discus with our master mod editor (c0br4)

https://discord.gg/yaaWenC9VM

**Comment by Spec47** [comment]
> we have upgraded the classname system, you have more choice to customize the mission and adding new units
> 
> please come on our discord to discus with our master mod editor (c0br4)
> 
> https://discord.gg/yaaWenC9VM

**Comment by Spec47** [comment]
Okey thank you
