### ISSUE TITLE
CUP USMC FOB does not appear 

### ISSUE THREAD

**Issue by PatZab** [tbox1911/Liberation-RX#64]
## How to reproduce:

1. Pick up FOB Container
2. Drop on desired destination
3. Trigger "Deploy FOB"

## Fix suggestion:

Change in classnames_west.sqf these lines to:
```
FOB_typename = "Land_Cargo_HQ_V1_F";
FOB_box_typename = "B_Slingload_01_Cargo_F";
```

**Comment by tbox1911** [comment]
hi,
thank a lot, that come from old arma2 model !
fixed in next release

**Comment by tbox1911** [comment]
fixed
