### ISSUE TITLE
Bug: You can take the loadout for free with Edit Loadout

### ISSUE THREAD

**Issue by lynhan4530** [tbox1911/Liberation-RX#65]
Like the title, player can cheat their way to get loadout for free

**Mods:**
1. ACE
2. CUP USMC

**Reproduce:**
1. Spawn at base/FOB
3. Open Arsenal via Action Menu
4. Choose Edit Loadout
5. Get the loadout you want, just different from the current one you have
6. Close the Arsenal Interface

**Expectation result:**
You will be notified that you paid for the loadout you have chosen like Take Loadout. Ammo count is deducted based on the loadout you have taken.

**Reality:**
The ammo counts do not change after you got your loadout, close the arsenal.

**Comment:**
I took a look in the "scripts\client\actions\open_arsenal.sqf" line 149 and I saw that the file already called for the payLoadout function after you close the edit_loadout (condition edit_loadout is false if it is not open). But I can't find what defines this variable or, isn't it compatible with ACE.

Please let me know.

**Comment by tbox1911** [comment]
hi,
thanks for reporting, I made some upgrade on pay_loadout function few days agao,
 I'll retest your issue

I tell you when it's fixed

**Comment by tbox1911** [comment]
edit: as you can see in the code, when ACE is enable there is no call to pay_loadout !
maybe I've just forgot to add the call, or there is another reason

**Comment by tbox1911** [comment]
Hi

I've just finish a patch that should fix your issue

please update and retest please :)

**Comment by lynhan4530** [comment]
Nice, the issue is fixed. But another problem came out. I dunno if I set the parameter wrong or something.

Same mod set but the arsenal show the vanilla loadout. While edit show ACE loadout.

**Comment by tbox1911** [comment]
hi maybe the filtering don't work with ace (yet!)

check the server option : 
EnableArsenal = 1; 
LimitedArsenal = 1;

try by setting them to zero (0)

**Comment by lynhan4530** [comment]
Well, more on that later. But I found another bug. Dunno what caused it. I will post another issue up
