### ISSUE TITLE
Question: why uniforms disappeared from arsenal ?

### ISSUE THREAD

**Issue by rushfly** [tbox1911/Liberation-RX#66]
All uniform disappeared from arsenal when I  enabled filter CUP in the Mission Options. In fact, all the original items have disappeared, leaving only CUP items. 
How can I keep the original items and CUPs using the blacklist  as the same time?

**Comment by tbox1911** [comment]
when "EnableFilterxxx" is enabled , the game will only kept items from the Mod

try by disabling the EnableFilterCUP params,

you should have all a3 items + cup items

**Comment by rushfly** [comment]
No, I can't found any cup items when I disabling the EnableFilterCUP params.

**Comment by tbox1911** [comment]
that strange !
whit these settings (default)
![image](https://user-images.githubusercontent.com/3987090/161594162-44d0e489-694a-4f15-a9cb-1d89e6e67635.png)

you should have cup + arma3 items
![image](https://user-images.githubusercontent.com/3987090/161594338-31543353-3c95-4caa-b656-c371269e885f.png)


feel free to come on our discord to discuss about this
https://discord.gg/uCRzJ7wauR

**Comment by tbox1911** [comment]
any news ?
