### ISSUE TITLE
Loadout not apply when selecting new item in Arsenal

### ISSUE THREAD

**Issue by lynhan4530** [tbox1911/Liberation-RX#68]
Mods:
ACE
CUP USMC

Reproduce:
Spawn and dead, by any means of course
Open Arsenal
Edit Arsenal
Pick whatever item you want.
Close the arsenal to confirm the transaction.
You should have that item and your ammo will be deducted

Reality:
The ammo count is deducted but it just forces back to the Preset Loadout (default).

Comment:
I add some fixed-price items and some more vehicles in the shop. I don't know if this affects ACE Arsenal we using.
The only fix to this current is whenever you die, you have to out of the lobby and get back in.
Or can I somehow use BI Arsenal instead of ACE but still keep the ACE function? I would love to if that solve the problem for the moment

**Comment by lynhan4530** [comment]
Nah, it still there.

And ACE medical kinda fucked up.

**Comment by tbox1911** [comment]
ok, it seems that my arsenal features (filter, price, etc) is not compatible with ACE :(

i'll try to find a workaround

**Comment by lynhan4530** [comment]
Hi, I just want to check in if have any update on the Arsenal yet ?

**Comment by tbox1911** [comment]
hi, a patch have been submitted to add more compat with ACE
could you retry with the latest pbo please

**Comment by lynhan4530** [comment]
it worked! Yay
But:
1. The ACE damage was disabled. No way to revive, or treating wound
2. When I respawned with a Loadout already saved (spawned with loadout), the ammo was not reduced

**Comment by tbox1911** [comment]
we're on the good path ! :)

I'll investigate the issue you have

**Comment by tbox1911** [comment]
could you retry with the latest pbo please

according to the ace doc, LRX will no install handle damage EH
