### ISSUE TITLE
Dedicated server stuck with player loading data when parameters are changed from default

### ISSUE THREAD

**Issue by AnonEstranho** [tbox1911/Liberation-RX#69]
Hello. As my title says, the players stay stuck with an almost black screen saying loading playing data. This happens when I change the parameters via server.cfg in my local dedicated server. If I don't alter the parameters, the mission works fine. I'm using Tanoa, didn't test in others.

Thank you.

**Comment by tbox1911** [comment]
hi,

what parameter do that ?

**Comment by AnonEstranho** [comment]
I posted the parameters in [pastebin](https://pastebin.com/3y6Q5WWg).

**Comment by tbox1911** [comment]
I've just tested with your params, work fine, please update your pbo and retry

note: value updated
CleanupVehicles = 1800;       // Cleanup abandoned vehicles outside FOB
Revive = 3;                            // FAR revive 
AdminMenu = 1;                    // Enable the Admin Menu  (replace Cheatmenu)


note: first startup can tale up to 1minute

**Comment by AnonEstranho** [comment]
I updated the pbo and tried again, still not working when using custom params.

Here's the [server.cfg](https://pastebin.com/dDkxCUa1) and the [startup command line](https://pastebin.com/uQTbdF3p).

I can't find what's wrong.

**Comment by AnonEstranho** [comment]
I think the problem is RHS. When I don't choose it as a mod preset, the server works fine. 

[Here's the server log when it loads your mission.](https://pastebin.com/F2tUma2T)

**Comment by tklein1801** [comment]
> I think the problem is RHS. When I don't choose it as a mod preset, the server works fine.
> 
> [Here's the server log when it loads your mission.](https://pastebin.com/F2tUma2T)

Where can I change the mod preset in this mission?

**Comment by tbox1911** [comment]
thx for the logfile, very usefull !!

I'll fix the bug "File A3\modules_f\HC\data\scripts\hc.sqf..., line 71"

I tell you when it's done

**Comment by tbox1911** [comment]
I push an update, please could you retry ?

**Comment by tklein1801** [comment]
I had the same problem. Using the new mission and using the correct parameters was able to fix the problem for me.

**Comment by AnonEstranho** [comment]
Thank you, it works. But while testing, it seems the respawn tent mechanic isn't working. I can't find it in the redeploy menu. Is this normal behaviour?

**Comment by AnonEstranho** [comment]
> You can only use an mobile respawn in a specific interval. If you just spawned on an mobile respawn they won't show up until the timer is finished (as far as I know)

But I can choose every point, including mobile respawn (heli), with the exception of the tents, which don't show up. They allow me to redeploy from them or halo jump, but they don't seem to act as a spawn point.

**Comment by tbox1911** [comment]
maybe the tent is too close a FOB ?

**Comment by tklein1801** [comment]
close?
