### ISSUE TITLE
Respawn on some FOBs and Bases not work. Building function not work.

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#7]
Please, could you check? My players reporting me a problems above. I've checked my changes and don't see any issues on my side.
Players can move an already built objects, but can not create a new.

It is happening for me since the commit https://github.com/tbox1911/Liberation-RX/commit/e252315a63517e80679c44b3faff09f3cf07fe3c and further

**Comment by tbox1911** [comment]
hi, I take a look at this
Iv' made some changes that can do that !

please retry with the latest version, and tell me if it persist

**Comment by Varrkan82** [comment]
I've tried the latest version by myself. Just merged your changes. There is no building menu at all, no Admin menu and no relocation menu too.

**Comment by tbox1911** [comment]
Hi, 
I've tested this morning with the latest version (dedicated/hosted), 
so far so good, everything seems to work.  (Respawn/Action Menu)

can you send me your pbo, I can test it on my PC

Happy new year :)

**Comment by Varrkan82** [comment]
> Hi,
> I've tested this morning with the latest version (dedicated/hosted),
> so far so good, everything seems to work. (Respawn/Action Menu)
> 
> can you send me your pbo, I can test it on my PC
> 
> Happy new year :)

Yes, sure. I even can give you access to my private repository with translations. 
Here is a direct link to PBO file https://mega.nz/file/lU1nBAxI#Iv-2zCBFEKkBZVEh3p6QcE_sIsd0lKSF90ntMAaiMsY

**Comment by tbox1911** [comment]
ok, got it!

let's see :)

i'll keep you in touch

**Comment by tbox1911** [comment]
a hint: start your arma3 client whith " -showScriptErrors"

you'll find in rpt file: 
`11:45:43 Error in expression <ad.sqf","follow",-635,false,true,"",""]
_id_actions set [6, _idact];
_idact = pl>
11:45:43   Error position: <_id_actions set [6, _idact];
_idact = pl>
11:45:43   Error ; manquant
11:45:43 File mpmissions\__cur_mp.Altis\scripts\client\actions\action_manager.sqf..., line 94`

and it's true !
you miss the ';' at the end of line 93

**Comment by tbox1911** [comment]
btw, you make a great job !!

**Comment by Varrkan82** [comment]
> a hint: start your arma3 client whith " -showScriptErrors"
> 
> you'll find in rpt file:
> `11:45:43 Error in expression <ad.sqf","follow",-635,false,true,"",""] _id_actions set [6, _idact]; _idact = pl> 11:45:43 Error position: <_id_actions set [6, _idact]; _idact = pl> 11:45:43 Error ; manquant 11:45:43 File mpmissions\__cur_mp.Altis\scripts\client\actions\action_manager.sqf..., line 94`
> 
> and it's true !
> you miss the ';' at the end of line 93

Thank you a lot. Just gained acces to my PC yesterday evening and started to test my hcanges mysqlves. But in a late night this thought wasn't visited my brain. Thank you!

**Comment by Varrkan82** [comment]
> btw, you make a great job !!

And I'm trying to keep it up to date. :)

**Comment by tbox1911** [comment]
hehe, know that :) 
new year's day damage !

**Comment by Varrkan82** [comment]
Fixed. Thank you!
