### ISSUE TITLE
[BUG] Abandoned base objects spawn

### ISSUE THREAD

**Issue by tklein1801** [tbox1911/Liberation-RX#71]
## Description

_For testing purposes I placed my FOB in the abandoned base. There are already a few objects (containers, chairs & workbenches) there from the start, which are intended to decorate the base or are intended for supply. Every time I connect to the server, they spawn again and thus double or in the case of the containers explode due to the collision with each other._

## Photos

|1|2|3|
|--|--|--|
|![pic 1](https://files.dulliag.de/share/arma3_x64_QBjLzY73MP.jpg)|![pic 1](https://files.dulliag.de/share/arma3_x64_pHFHs3grxf.jpg)|![pic 1](https://files.dulliag.de/share/arma3_x64_JDSBiQ1PVg.jpg)|

**Comment by tbox1911** [comment]
edit object properties

![image](https://user-images.githubusercontent.com/3987090/163239860-e29c9219-b8bf-43e6-b18c-e5ebb058151c.png)

**Comment by tklein1801** [comment]
Thank you, problem solved
