### ISSUE TITLE
The medic starts without equipment

### ISSUE THREAD

**Issue by Maciccio** [tbox1911/Liberation-RX#84]
Hi Tbox. Sorry for posting several issues. Maybe because I downloaded the release versions from a few years ago? Now I have found that with GitHub Desktop I can always download the updated version.

Now I only have one question to ask, only the player in the Medic slot starting with 0 gear?
The commander, group leader, engineer, marksman, all start with their basic kit, the doctor doesn't.
Is it a problem that only I have? If so, why do these things happen to me? Maybe because I have the server on a VPS?
If so, can you tell me the file to change the doctor's equipment?

Thank you and excuse me

**Comment by tbox1911** [comment]
hi, you're welcome !!

LRX is in active development, so I recommand you to keep your version updated !

please come on our discord to explain in details what happen to you
https://discord.gg/uCRzJ7wauR

You should not face this issue, tell me what map you are using and if you add some Mod ?

**Comment by Maciccio** [comment]
Unfortunately I can't speak English, I can only write
The discord link is not working :(
