### ISSUE TITLE
Mod Filter is missing some items

### ISSUE THREAD

**Issue by lynhan4530** [tbox1911/Liberation-RX#86]
Sorry for not replying to the previous issue but the damage has proper behavior with ACE now.
Now for the Mod Filter, for example, CUP doesn't show any smoke grenade. A lot of unsued launchers and no name item (vest, uniform that uses for dev) all show up and messed up the arsenal list.
And the list not show yet haha (not big issue)
Suggest you made a custom arsenal or preset arsenal like what the original liberation did. 

2nd issue (yes sorry but I'm a little lazy)
When I equip an item that cost ammo, I click Close arsenal -> I pay for that item - Cool
But I haven't used it yet. So if at that moment, I return it to the arsenal by the mean of reopening the arsenal -> choose the slot -> select equip nothing -> Click close arsenal -> I should get back the ammo, right?
This is more like a gameplay design issue but I really want to have a chance to undo my mistake.

Thank you for replying to all of my tickets.

**Comment by tbox1911** [comment]
hi, you're welcome !
- I rewrite the Arsenal mechanics, much more simpler to use
  - one black list (to remove unwanted items)
  - one white list (to add missing items)

- there is no refund with the Arsenal :)

**Comment by lynhan4530** [comment]
I have modified the arsenal file but somehow it has not affected
