### ISSUE TITLE
Players banned for shooting to teammates bodies

### ISSUE THREAD

**Issue by Varrkan82** [tbox1911/Liberation-RX#9]
Hi.
Guys reporting me they are punished for TK while they are shooting into a bodies of a dead teammates. For example - if a grenade or an air-bomb exploded  near a dead teammate or something like that. Or if they are pointing an air strike with a laser and the dead teammate is in a explosion radius.

**Comment by tbox1911** [comment]
add a check in TK protect to skip Unconscious units

**Comment by Varrkan82** [comment]
> add a check in TK protect to skip Unconscious units
> 
> can you re test ?

Thanks. I'll setup a new version on my server and ask guys to test it. Can't do it myself till the evening. 

Also - could you commit changes regarding to an issues at least with issue number? It will help to recognise changes more accurate. Thank you.

**Comment by tbox1911** [comment]
i'll try to track my commit correctly :)

**Comment by Varrkan82** [comment]
This fixed. Thanks.
