### ISSUE TITLE
Friendly fire messages and punishments when hitting players while remote controlling enemy units using Zeus

### ISSUE THREAD

**Issue by logimy** [tbox1911/Liberation-RX#90]
Recently i tried to create a custom mission with zeus and encountered a problem:
Whenever i hit a player with remote controlled unit using Zeus, server pops out messages from TK system about me is trying to friendly fire friendly unit. 

This creating a lot of problems for players because of many actions appear in their scroll menu and this kind of behavior is hitting hard the immersion.

Is there a way to filter out remotely controlled units from TK system checks?

**Comment by logimy** [comment]
It should be as easy as changing the line `_killer = _instigator` inside only 3 files 
`addons\PAR\PAR_global_functions.sqf`, 
`scripts\shared\damage_manager.sqf`,
`scripts\shared\kill_manager.sqf`
to:
```
if (!isNull (getAssignedCuratorLogic _instigator)) then {
	    _killer = _instigator;
	} else {
	    _killer = _unit;
	};
```

**Comment by tbox1911** [comment]
hi, 
thanks for the info and patch
I'll patch the tree files you mention

will be available in next build

**Comment by tbox1911** [comment]
build is out, you can test

**Comment by logimy** [comment]
Everything works as intended! Thanks for your time!
