### ISSUE TITLE
Getting "Mission Failed" On Launch

### ISSUE THREAD

**Issue by Kylerh15** [tbox1911/Liberation-RX#93]
Just tried to give this mission a try on a deticated server and got hit with a Mission Failed screen after selecting role, when attempting to continue we just get hit with another Mission Failed screen, I then tried to subscribe to the mission on the workshop and load it locally but again get hit with the Mission Failed screen.

Mission Version: Liberation_RX.Takistan.pbo v0.0.9
Arma Version: Latest
Mods Enabled: 
CBA_A3
CUP Terrains - Core
CUP Terrains - Maps
Project OPFOR
RHSAFRF
RHSUSAF
RHSGREF
RHSSAF
Enhanced Movement
Enhanced Movement Rework
Enhanced Video Settings
JSRS SOUNDMOD
JSRS SOUNDMOD - RHS AIO Mod Pack Sound Support

**Comment by tbox1911** [comment]
hello,

could you try to wipe the old savegame, 
in mission parameters, at the bottom, you have two settings to wipe savegame

if that not fix your issue, please send me your server report file (.rpt) 

I'll take a look
