### ISSUE TITLE
Prisoner gives no intel after interrogation...

### ISSUE THREAD

**Issue by jesst3r** [tbox1911/Liberation-RX#98]
Greetings tried many times, but after interrogation i'm receiving notification that prisoner have interrogated and i've got +6 intel (for example). But nothing changed (still got 0 intel)

**Comment by tbox1911** [comment]
hi,
thanks for reporting, I'll investigate this issue

**Comment by jesst3r** [comment]
> hi, thanks for reporting, I'll investigate this issue

Found the cause of that problem. After disabling the headless client, the issue went away.

**Comment by tbox1911** [comment]
ok, interesting, maybe I forgot something with HC
I'll to fix it

**Comment by tbox1911** [comment]
I think I fix the issue, please retry with the latest build and tell me
